### ISSUE TITLE
Error de políticas de firma para Face

### ISSUE THREAD

**Issue by rafaapli** [carlosga/FacturaE#1]
He comprobado que los ficheros firmados son correctos para otras plataformas que recogen facturae, pero para Face han cambiado algo y da error en la politica de firma. Puedes comprobarlo en esta web https://valide.redsara.es/valide/validarFirma/ejecutar.html

**Comment by carlosga** [comment]
En el validador de la web de FacturaE ( http://sedeaplicaciones2.minetur.gob.es/FacturaE/ ) si validan correctamente.

Según la documentacion de FacturaE, hay dos formatos para la política de firma (v3.1), XAdES-EPES ( que es el que está implementado en el proyecto ) y XAdES-XL.

Es posible que esa Web espere la política de firma en un formato distinto ... y por eso de error al validar la factura

**Comment by rafaapli** [comment]
Es verdad, en ese portal ya había probado y si valida, y yo tenia un desarrollo hecho que me creaban ese tipo de firma, pero el portal mas importante a nivel nacional para Facturae es el de la administración publica(Face) y han cambiado la comprobación de la politica y da error. 
Probablemente lo que falta es meter el signintime y el signinrol, por ejemplos que he visto.
¿Como podría añadirlo en tu proyecto para probar?

**Comment by gaeinformatica** [comment]
Desde el día 1 de junio en FACe se han realizado algunos cambios que afectan al funcionamiento de las empresas para entregar las facturas. 

"La Plataforma de validación de certificados y firmas (@firma) validará de forma estricta el esquema del formato EPES, que es el utilizado en las facturas electrónicas (FacturaE). En concreto:

1. Se validará el orden de los de los elementos incluidos en el atributo <xades:SignedSignatureProperties>.

Las especificaciones XAdES 1.3.2 definen el elemento "SignedSignatureProperties" como una lista ordenada de los siguientes elementos, todos con carácter opcional: 
* SigningTime

* SigningCertificate

* SignaturePolicyIdentifier

* SignatureProductionPlace

* SignerRole

Se validará de modo estricto de contenido del campo SignerRole"

**Comment by carlosga** [comment]
Ok, parece que para que esa la web del post original valide bien, basta con indicar correctamente el valor de SigningTime, voy a subir unos cambios para que se genere correctamente y se pueda indicar también los datos de SignerRole.

**Comment by jmllinas** [comment]
Muchas gracias por tu trabajo y por subir los cambios.

Estoy un poco perdido con este tema.

Me podriais poner un pequeño ejemplo de como se rellena el .Sign(cert, signerRole) El signerRole es el que desconozco.

Un cordial saludo.
