### ISSUE TITLE
Una vez firmada la factura y almacenada en formato xsig, ¿cómo enviar a facturae?

### ISSUE THREAD

**Issue by overlinejota** [carlosga/FacturaE#2]
Gracias Carlos por compartir tu gran trabajo.

**Comment by carlosga** [comment]
Hacer mucho que no veo esa parte, sino me equivoco en la propia web de facturae hay información de como hacer los envios ( dependiendo del destinatario ):

https://www.facturae.gob.es/Paginas/Index.aspx
https://www.facturae.gob.es/face/Paginas/FACE.aspx

**Comment by overlinejota** [comment]
Gracias de nuevo Carlos
