### ISSUE TITLE
Bug in Sign method?

### ISSUE THREAD

**Issue by RaulLuna** [carlosga/FacturaE#3]
Hi, Carlos
First of all, thanks for this project (I´m newbie in GitHub)

I´ve tried to compile it in my Visual Studio 2022 but in the Program.cs,  line 84 , this code 

`.Sign(certificate)` 

don´t recognize it and mark it like and error

Can you help me?.

Thanks in advance
Raúl

**Comment by carlosga** [comment]
Hi, without the error message it's going to be difficult to help, if you can send the error message please.
