### ISSUE TITLE
Demo invoice generated not validated by Government validator

### ISSUE THREAD

**Issue by milnet92** [carlosga/FacturaE#4]
The invoice that is generated (or any other invoice generated) signed with this library does not pass validation using the Government official validator.

The format of the invoice is correct, but the certificate fails.

The validator can be accessed using this link: https://face.gob.es/es/facturas/validar-visualizar-facturas

**Comment by carlosga** [comment]
Hi, looks as being validate correctly from these (with the latest changes):

https://valide.redsara.es/valide/validarFirma/ejecutar.html;jsessionid=4998254F9F783C791178ADC7480D6102
https://face.gob.es/es/facturas/validar-visualizar-facturas
